debugging

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,3 +11,6 @@ jobs:
 
       - name: Run a one-line script
         run: echo "Hello, world!"
+        
+      - name: Simulate an error
+        run: echo "About to fail" ; exit 1
